default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development_tickets

test:
  <<: *default
  database: test_tickets

production:
  <<: *default
  database: production_tickets
